name: client-scrtp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: update and install dependencies
      run: sudo apt update && sudo apt install libglfw3 libglfw3-dev
    - name: make client
      run: make client
